volumes:
    database:
services:
    web:
        image: boudzmarcellino/phpapache
#        build:
#            context: .
#            dockerfile: phpApache.dockerfile
        container_name: webserver
        ports:
            - 80:80
        volumes: 
            - /home/user/Documents/www/schoolweb:/var/www/html
#            - C:\Users\user\Documents\www\schoolweb:/var/www/html
    database:
        image: mysql
        container_name: dbserver
        command: ["mkdir", "/db" ]
        working_dir: /db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=Mysql 
            - MYSQL_TCP_PORT=3306
        ports:
            - 3306:3306
        volumes:
            - database:/var/lib/mysql:rw
            - /home/user/Documents/www/schoolweb/database:/db
